// Dependency-free, XSS-safe Markdown → React renderer for Deneb's chat replies,
// mail bodies, and wiki/doc previews. Covers GFM at the level the native client
// renders: ATX headings, bold/italic/strikethrough, inline + fenced code (with a
// language label + copy), links/images/autolinks (http/https/mailto only),
// nested ordered/unordered lists, task-list checkboxes, blockquotes (with block
// content), aligned GFM tables, hard line breaks, backslash escapes, and rules.
//
// The grammar (text → Block AST) lives in markdown/parse.ts; this file is the
// AST → React pass. Output is React elements so every text node is auto-escaped —
// no HTML sanitizer needed, and link/image schemes are whitelisted. The ONE
// exception is KaTeX math: its `renderToString` HTML is injected via
// dangerouslySetInnerHTML. That is safe because the HTML is generated by KaTeX
// from the LaTeX source (not passed-through user HTML), and `trust` defaults to
// false so `\href`/`\url` and other URL-injecting macros are disabled — only
// KaTeX's own span/MathML markup is produced. We render our own GFM rather than
// pulling react-markdown + remark (and its build-script supply-chain gate); KaTeX
// is the single math dependency.
import { type CSSProperties, type ReactNode, useState } from "react";
import katex from "katex";
import { type Align, type Block, type ListItem, parseBlocks } from "@/markdown/parse";
import { Icon } from "./Icon";

// Only these schemes render as live links/images; anything else stays plain text
// so a `javascript:`/`data:` URL can never become a clickable or fetchable node.
function safeHref(url: string): string | null {
  const u = url.trim();
  return /^(https?:\/\/|mailto:)/i.test(u) ? u : null;
}

// Earliest-match inline tokenizer. At each step the pattern that OPENS first wins
// (ties broken by array order), so escapes and images beat the weaker emphasis
// markers. Each alternative captures its inner text for recursive rendering.
const INLINE: { kind: string; re: RegExp }[] = [
  { kind: "esc", re: /\\([\\`*_{}[\]()#+\-.!~>|"'$])/ },
  { kind: "br", re: /\n/ },
  { kind: "image", re: /!\[([^\]]*)\]\(([^)\s]+)\)/ },
  { kind: "code", re: /`([^`]+)`/ },
  // Inline math: $…$ with currency guards — no space just inside the delimiters
  // and the closer not followed by a digit, so "$5 … $10" / "$100" stay text.
  { kind: "math", re: /\$(?![\s$])((?:\\.|[^$\\\n])+?)(?<!\s)\$(?!\d)/ },
  { kind: "autolinkAngle", re: /<((?:https?:\/\/|mailto:)[^>\s]+)>/ },
  { kind: "link", re: /\[([^\]]+)\]\(([^)\s]+)\)/ },
  { kind: "strike", re: /~~([^~]+)~~/ },
  { kind: "bold", re: /\*\*([^*]+)\*\*|__([^_]+)__/ },
  { kind: "italic", re: /\*([^*\n]+)\*|\b_([^_\n]+)_\b/ },
  { kind: "autolink", re: /(https?:\/\/[^\s<>)\]]+)/ },
];

function renderInline(text: string, key: string): ReactNode[] {
  const out: ReactNode[] = [];
  let rest = text;
  let n = 0;
  while (rest.length > 0) {
    let best: { idx: number; len: number; kind: string; m: RegExpExecArray } | null = null;
    for (const { kind, re } of INLINE) {
      const m = re.exec(rest);
      if (m && (best === null || m.index < best.idx)) best = { idx: m.index, len: m[0].length, kind, m };
    }
    if (!best) {
      out.push(rest);
      break;
    }
    const k = `${key}-${n++}`;
    const { kind, m } = best;
    // Text before the token. For a line break, strip the trailing hard-break
    // marker (2+ spaces or a backslash) so it doesn't render as literal space.
    let before = rest.slice(0, best.idx);
    if (kind === "br") before = before.replace(/[ \t]+$|\\$/, "");
    if (before) out.push(before);

    if (kind === "esc") {
      out.push(m[1]);
    } else if (kind === "br") {
      out.push(<br key={k} />);
    } else if (kind === "image") {
      const src = safeHref(m[2]);
      out.push(src ? <img key={k} className="md-img" src={src} alt={m[1]} loading="lazy" /> : m[1]);
    } else if (kind === "code") {
      out.push(
        <code key={k} className="md-code">
          {m[1]}
        </code>,
      );
    } else if (kind === "math") {
      out.push(
        <span
          key={k}
          className="md-math"
          // KaTeX-generated markup from the LaTeX source (trust:false) — safe; see file header.
          dangerouslySetInnerHTML={{ __html: katex.renderToString(m[1], { throwOnError: false }) }}
        />,
      );
    } else if (kind === "autolinkAngle" || kind === "autolink") {
      let url = m[1];
      let trail = "";
      if (kind === "autolink") {
        const t = /[.,;:!?)\]}'"]+$/.exec(url);
        if (t) {
          trail = t[0];
          url = url.slice(0, -trail.length);
        }
      }
      const href = safeHref(url);
      out.push(
        href ? (
          <a key={k} href={href} target="_blank" rel="noreferrer noopener">
            {url}
          </a>
        ) : (
          url
        ),
      );
      if (trail) out.push(trail);
    } else if (kind === "link") {
      const href = safeHref(m[2]);
      out.push(
        href ? (
          <a key={k} href={href} target="_blank" rel="noreferrer noopener">
            {renderInline(m[1], k)}
          </a>
        ) : (
          renderInline(m[1], k)
        ),
      );
    } else if (kind === "strike") {
      out.push(<del key={k}>{renderInline(m[1], k)}</del>);
    } else if (kind === "bold") {
      out.push(<strong key={k}>{renderInline(m[1] ?? m[2], k)}</strong>);
    } else {
      out.push(<em key={k}>{renderInline(m[1] ?? m[2], k)}</em>);
    }
    rest = rest.slice(best.idx + best.len);
  }
  return out;
}

// A fenced code block: language label + copy affordance over a monospaced pre.
function CodeBlock({ lang, text }: { lang: string; text: string }) {
  const [copied, setCopied] = useState(false);
  async function copy() {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1200);
    } catch {
      /* clipboard blocked — no-op */
    }
  }
  return (
    <div className="md-codeblock">
      <div className="md-codebar">
        {lang ? <span className="md-codelang">{lang}</span> : <span />}
        <button type="button" className="md-copy" onClick={copy} aria-label="코드 복사">
          <Icon name="copy" size={12} />
          {copied ? "복사됨" : "복사"}
        </button>
      </div>
      <pre>
        <code data-lang={lang || undefined}>{text}</code>
      </pre>
    </div>
  );
}

function renderItemBody(item: ListItem, key: string): ReactNode {
  // Tight item (single paragraph) renders inline so list rows stay compact;
  // a multi-block item (nested list, multiple paragraphs) renders its blocks.
  if (item.children.length === 1 && item.children[0].type === "para") {
    return renderInline(item.children[0].text, key);
  }
  return item.children.map((b, j) => renderBlock(b, `${key}-${j}`));
}

function renderList(b: Extract<Block, { type: "list" }>, key: string): ReactNode {
  const hasTask = b.items.some((it) => it.task);
  const children = b.items.map((it, j) => {
    const body = renderItemBody(it, `${key}-${j}`);
    return it.task ? (
      <li key={j} className="md-task">
        <input type="checkbox" checked={!!it.checked} disabled readOnly />
        <span>{body}</span>
      </li>
    ) : (
      <li key={j}>{body}</li>
    );
  });
  const cls = hasTask ? "md-tasklist" : undefined;
  return b.ordered ? (
    <ol key={key} className={cls} start={b.start && b.start !== 1 ? b.start : undefined}>
      {children}
    </ol>
  ) : (
    <ul key={key} className={cls}>
      {children}
    </ul>
  );
}

function renderBlock(b: Block, key: string): ReactNode {
  switch (b.type) {
    case "heading": {
      const Tag = `h${Math.min(b.level + 2, 6)}` as "h3" | "h4" | "h5" | "h6";
      return <Tag key={key}>{renderInline(b.text, key)}</Tag>;
    }
    case "code":
      return <CodeBlock key={key} lang={b.lang} text={b.text} />;
    case "hr":
      return <hr key={key} />;
    case "quote":
      return <blockquote key={key}>{b.children.map((c, j) => renderBlock(c, `${key}-${j}`))}</blockquote>;
    case "list":
      return renderList(b, key);
    case "mathBlock":
      return (
        <div
          key={key}
          className="md-math-block"
          // KaTeX display-mode markup from the LaTeX source (trust:false) — safe; see file header.
          dangerouslySetInnerHTML={{ __html: katex.renderToString(b.text, { throwOnError: false, displayMode: true }) }}
        />
      );
    case "table":
      return (
        <table key={key} className="md-table">
          <thead>
            <tr>
              {b.header.map((h, j) => (
                <th key={j} style={alignStyle(b.align[j])}>
                  {renderInline(h, `${key}-h${j}`)}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {b.rows.map((row, r) => (
              <tr key={r}>
                {row.map((c, j) => (
                  <td key={j} style={alignStyle(b.align[j])}>
                    {renderInline(c, `${key}-${r}-${j}`)}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      );
    case "para":
      return <p key={key}>{renderInline(b.text, key)}</p>;
  }
}

function alignStyle(a: Align): CSSProperties | undefined {
  return a ? { textAlign: a } : undefined;
}

// Render Markdown text as safe React nodes. Plain text with no Markdown renders
// as a single <p>, so a bare reply stays a clean paragraph.
export function Markdown({ text }: { text: string }) {
  const blocks = parseBlocks(text);
  return <div className="md">{blocks.map((b, i) => renderBlock(b, `b${i}`))}</div>;
}
