// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TokenService ports the Tauri token_* commands (src-tauri/src/lib.rs). Registered
 * as a Wails service, its exported methods are callable from the frontend via the
 * generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * FromFile returns the canonical token the gateway writes to ~/.deneb/client_token
 * so the desktop app auto-connects without the user pasting it. Missing file → "".
 * @returns {$CancellablePromise<string>}
 */
export function FromFile() {
    return $Call.ByID(1952056322);
}

/**
 * Get returns the keychain token for account, or "" if none is stored.
 * @param {string} account
 * @returns {$CancellablePromise<string>}
 */
export function Get(account) {
    return $Call.ByID(806072600, account);
}

/**
 * Set persists the Deneb client token in the OS keychain (macOS Keychain /
 * Windows Credential Manager) rather than localStorage — DESIGN §6.
 * @param {string} account
 * @param {string} token
 * @returns {$CancellablePromise<void>}
 */
export function Set(account, token) {
    return $Call.ByID(2986285700, account, token);
}
